apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-argocd
  namespace: ci-cd-demo
spec:
  destination:
    namespace: demo-argocd
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: environments/dev
    repoURL: https://github.com/Monishkumar12/sonarqube-mo-ro.git
    targetRevision: master
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
